name: Build and Generate Swagger JSON

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: 1234
        ports:
          -  3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK  11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Spring Boot application
        run: ./gradlew bootRun --no-daemon &
        # We need to give the server some time to start up
        continue-on-error: true

      - name: Wait for server to start
        run: sleep  120

      - name: Generate Swagger JSON
        run: curl http://localhost:8080/v3/api-docs > swagger.json
        # Ensure that the server is still running when we attempt to access the Swagger JSON
        needs: build

      - name: Upload Swagger JSON
        uses: actions/upload-artifact@v2
        with:
          name: swagger-json
          path: swagger.json
